### ISSUE TITLE
Awesome Job!

### ISSUE THREAD

**Issue by dannyvassallo** [stvbuller/ToDoList#1]
Loving the style Steven! Amazing work. The only thing I saw is some funky indentation in some of your conditional logic, but that could just be github showing some funky formatting. Overall -- Incredible stuff. I'm impressed!

**Comment by stbuller** [comment]
Thanks for the feedback!

**Comment by dannyvassallo** [comment]
@stvbuller no problem! keep up the good work!

**Comment by stbuller** [comment]
Corrected the indentation issues in the conditional logic
